---
grails:
    profile: web
    codegen:
        defaultPackage: au.org.ala.dashboard
    config:
            locations:
                - file:/data/dashboard/config/dashboard-config.properties
                - file:/data/dashboard/config/dashboard-config.yml
                - file:/data/dashboard/config/dashboard-config.groovy
    spring:
        transactionManagement:
            proxies: false
    servlet:
        version: 3.0
    gorm:
        # Whether to autowire entities. 
        # Disabled by default for performance reasons.
        autowire: false         
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
#default_config: "/data/dashboard/config/dashboard-config.properties"
default_config: "D:/reinhardt/firma/Biodiversity/working/dashboard-config.properties"
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: true
    jmx:
        enabled: true

---
grails:
    cors:
        enabled: true
    mime:
        disable:
            accept:
                header:
                    userAgents: false
                       # - Gecko
                       # - WebKit
                       # - Presto
                       # - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: jsp
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
skin:
    layout: "ala-main"
    fluidLayout: true
    orgNameLong: "Biodiversitätsatlas Österreich"
    orgNameShort: "BAÖ"
privacyPolicy: "https://www.ala.org.au/about/terms-of-use/privacy-policy/"

---
security:
    cas:
        uriFilterPattern: "/alaAdmin.*"
        uriExclusionFilterPattern: "/images.*,/css.*,/js.*,/less.*"
        bypass: "true"

environments:
    development:
        grails:
            serverURL: "http://localhost:8080/dashboard"
        security:
            cas:
                appServerName: "http://localhost:8080/dashboard"
        dashboard:
            data:
                file: "D:/reinhardt/firma/Biodiversity/working/data.json"
        csv:
            temp:
                dir: "D:/reinhardt/firma/Biodiversity/working/csv/"
        zip:
            temp:
                dir: "D:/reinhardt/firma/Biodiversity/working/zip/"
    test:
        grails:
            serverURL: "http://nectar-dashboard-test.ala.org.au/"
        security:
            cas:
                appServerName: "https://auth.ala.org.au"
    production:
        grails:
            serverURL: "https://dashboard.ala.org.au/"
        security:
            cas:
                appServerName: "https://auth.ala.org.au"

biocache:
  baseURL: "https://biocache.ala.org.au/ws"
  webappURL: "https://biocache.ala.org.au"

ala:
  baseURL: "https://www.ala.org.au"

bie:
  #baseURL: "https://bie.ala.org.au"
  baseURL: "https://bie-ws.biodiversityatlas.at"
  searchPath: "/search"

spatial:
  baseURL: "http://spatial.ala.org.au"

logger:
  baseURL: "https://logger.ala.org.au"

collectory:
  baseURL: "https://collections.ala.org.au"

volunteer:
  baseURL: "https://volunteer.ala.org.au"

images:
  baseURL: "https://images.ala.org.au"

userDetails:
  baseURL: "https://auth.ala.org.au/userdetails"

bhl:
  baseURL: "http://biodiversitylibrary.org/"
  statsSelector: ".onlinestats"

headerAndFooter:
  #baseURL: "https://www.ala.org.au/commonui-bs3"
  baseURL: "https://core.biodiversityatlas.at"

dashboard:
    data:
        file: "/data/dashboard/data.json"

csv:
    temp:
        dir: "/data/dashboard/csv/"
zip:
    temp:
        dir: "/data/dashboard/zip/"

panels:
  recordsPanel: true
  datasetsPanel: true
  basisRecordsPanel: false
  collectionPanel: true
  dateRecordsPanel: true
  nslPanel: false
  spatialPanel: true
  statePanel: true
  mostRecordedSpeciesPanel: true
  typeSpecimensPanel: false
  barcodeOfLifePanel: false
  bhlPanel: false
  volunteerPortalPanel: false
  conservationStatusPanel: true
  recordsByDataProviderPanel: true
  recordsByInstitutionPanel: true
  occurrenceTreePanel: true
  recordsByLifeFormPanel: true
  recordsAndSpeciesByDecadePanel: true
  usageStatisticsPanel: true
  downloadsByReasonPanel: true
  downloadsBySourcePanel: true
  downloadsByUserTypePanel: true
  speciesImagesPanel: false
